### ISSUE TITLE
Fazer tela de boas vindas!

### ISSUE THREAD

**Issue by thiagopromano** [thiagopromano/prog1-1#7]
Faz bem bonito usando uma função plz!

**Comment by IgorGuilhermeC** [comment]
Desenvolvido a tela de boas vindas*

*Verificar uma forma mais simples de implementar a mesma

**Comment by thiagopromano** [comment]
Ficou show assim, eu faria uma função para imprimir uma barra de # só

**Comment by IgorGuilhermeC** [comment]
Entendi, acho que fica melhor mesmo

Depois implemento
