### ISSUE TITLE
Arquivos múltiplos

### ISSUE THREAD

**Issue by IgorGuilhermeC** [thiagopromano/prog1-1#8]
Como programo para web, tenho o costume de separar os arquivos e incluí-los no início do arquivo do principal, além de deixar mais organizado fica um código mais compacto.

Deixo como sugestão a ideia de criar arquivos múltiplos e inseri-los no começo do arquivo principal, assim, teríamos um código menor e mais limpo, incluímos os arquivos com as structs e com as funções visto que ao implementar as funções é gerada uma poluição visual.

Aguardo retorno.

**Comment by thiagopromano** [comment]
Do it!

**Comment by thiagopromano** [comment]
Mas daí tem que criar um arquivo make

**Comment by IgorGuilhermeC** [comment]
Ok, vou ver como faz isso e daí altero.

**Comment by thiagopromano** [comment]
Aproveita e coloca as structs e os typedefs em um .h

**Comment by IgorGuilhermeC** [comment]
Tudo bem, farei isso 😆

**Comment by IgorGuilhermeC** [comment]
Feito
